#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

mysql_ready() {
python << END
import sys
import MySQLdb
import os

try:
    MySQLdb.connect(
        db=os.environ['DATABASE_NAME'],
        user=os.environ['DATABASE_USER'],
        passwd=os.environ['DATABASE_PASSWORD'],
        host=os.environ['DATABASE_HOST'],
        port=int(os.environ['DATABASE_PORT']),
    )
except MySQLdb.OperationalError:
    sys.exit(-1)
sys.exit(0)
END
}

until mysql_ready; do 
    >&2 echo "waiting for MySQLdb to become available... :-("
    sleep 1
done
>&2 echo "MySQLdb is ready!!!!... :-)"

# Execute the command passed to the script
exec "$@"
