# Generated by Django 5.0.6 on 2024-05-28 23:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="air_conditioning",
            field=models.BooleanField(
                default=False,
                help_text="Air Conditioning",
                verbose_name="Air Conditioning",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="furnished",
            field=models.BooleanField(
                default=False, help_text="Furnished", verbose_name="Furnished"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="garage",
            field=models.IntegerField(
                default=1,
                help_text="Garage",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Garage",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="swimming_pool",
            field=models.BooleanField(
                default=False, help_text="Swimming Pool", verbose_name="Swimming Pool"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="bathroom",
            field=models.IntegerField(
                default=1,
                help_text="Bathroom",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Bathroom",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="bedroom",
            field=models.IntegerField(
                default=1,
                help_text="Bedroom",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Bedroom",
            ),
        ),
    ]
