# Generated by Django 5.0.6 on 2024-05-31 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0003_property_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="propertyviews",
            options={
                "verbose_name": "Views on Property",
                "verbose_name_plural": "Total Property Views",
            },
        ),
        migrations.RemoveField(
            model_name="property",
            name="air_conditioning",
        ),
        migrations.AlterField(
            model_name="property",
            name="advert_type",
            field=models.CharField(
                choices=[("SALE", "Sale"), ("RENT", "Rent"), ("AUCTION", "Auction")],
                default="SALE",
                max_length=10,
                verbose_name="Advert Type",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="photo1",
            field=models.ImageField(
                blank=True,
                default="/interior_sample.jpg",
                upload_to="property/photo1",
                verbose_name="Photo 1",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="photo2",
            field=models.ImageField(
                blank=True,
                default="/interior_sample.jpg",
                upload_to="property/photo2",
                verbose_name="Photo 2",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="photo4",
            field=models.ImageField(
                blank=True,
                default="/interior_sample.jpg",
                upload_to="property/photo4",
                verbose_name="Photo 4",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="Price"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("Single_Room", "Single Room"),
                    ("Double_Room", "Double Room"),
                    ("Bedsitter", "Bedsitter"),
                    ("One_Bedroom", "One Bedroom"),
                    ("Two_Bedroom", "Two Bedroom"),
                    ("Three_Bedroom", "Three Bedroom"),
                    ("APARTMENT", "Apartment"),
                    ("HOUSE", "House"),
                    ("LAND", "Land"),
                    ("Office", "Office"),
                    ("STUDIO_APARTMENT", "Studio Apartment"),
                    ("Warehouse", "Warehouse"),
                    ("VILLA", "Villa"),
                    ("Commercial", "Commercial"),
                    ("FLAT", "Flat"),
                    ("BUNGALOW", "Bungalow"),
                    ("PENTHOUSE", "Penthouse"),
                    ("Other", "Other"),
                ],
                default="Single_Room",
                max_length=40,
                verbose_name="Property Type",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="agent_buyer",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Agent, Renter, Seller or Buyer",
            ),
        ),
    ]
