# Generated by Django 5.0.6 on 2024-05-31 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0004_alter_propertyviews_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="final_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Price including tax",
                max_digits=12,
                verbose_name="Final Price",
            ),
        ),
    ]
