# Generated by Django 5.0.6 on 2024-05-31 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ratings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rating",
            name="comment",
            field=models.TextField(default="Goo work", verbose_name="Comment"),
            preserve_default=False,
        ),
    ]
